# Introduction to Pandas 
Docs - https://pandas.pydata.org/docs/reference/
Function - https://pandas.pydata.org/docs/reference/io.html


## What is Pandas?
The Pandas library is built on NumPy and provides easy-to-use data structures and data analysis tools for the Python programming language.

## Pandas Series
A **one-dimensional** labeled array a capable of holding any data type

## Pandas DataFrame
A **two-dimensional** labeled data structure with columns of potentially different types
![Pandas](../img/pandas.png)

## Advantages of Pandas
- Data representation
- Less writing and more work done
- An extensive set of features
- Efficiently handles large data
- Makes data flexible and customizable
- Made for Python


In [1]:
# Conventional  way to import pandas 
import pandas as pd 

In [2]:
# Check pandas version
pd.__version__

'1.3.4'

In [3]:
# Show version of all packages 
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-39-generic
Version          : #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3

## Creating Series

In [4]:
import numpy as np

In [5]:
A = np.array([3, 4, 5])
A 

array([3, 4, 5])

In [6]:
type(A)

numpy.ndarray

In [7]:
# Create Series 
s1 = pd.Series([3, 6, 9, 12, 20, 21])
s1

0     3
1     6
2     9
3    12
4    20
5    21
dtype: int64

In [8]:
# Check type 
type(s1)

pandas.core.series.Series

In [9]:
# To see values 
s1.values

array([ 3,  6,  9, 12, 20, 21])

In [10]:
# To see index/keys 
s1.index

RangeIndex(start=0, stop=6, step=1)

In [17]:
# Creating labeled series 
s2 = pd.Series([200000, 300000, 4000000, 500000], index=['A', 'B', 'C', 'D'])

In [18]:
s2

A     200000
B     300000
C    4000000
D     500000
dtype: int64

In [19]:
s2.values

array([ 200000,  300000, 4000000,  500000])

In [20]:
s2.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [21]:
# Indexing
s2['A']

200000

In [22]:
# Boolean indexing
s2[s2 > 700000]

C    4000000
dtype: int64

## Creating DataFrame 

In [23]:
# Create a DataFrame 
data = {'Country': ['Belgium', 'India', 'Brazil'],
        'Capital': ['Brussels', 'New Delhi', 'Brasília'],
        'Population': [11190846, 1303171035, 207847528]
}

df = pd.DataFrame(data, columns=["Country", "Capital", "Population"])

In [24]:
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528

In [25]:
# Check type 
type(df)

pandas.core.frame.DataFrame

In [26]:
# Indexing
df["Country"]

0    Belgium
1      India
2     Brazil
Name: Country, dtype: object

In [28]:
# or 
df.Population

0      11190846
1    1303171035
2     207847528
Name: Population, dtype: int64

In [29]:
# type 
type(df["Country"])

pandas.core.series.Series

In [30]:
# type 
type(df["Capital"])

pandas.core.series.Series

In [ ]:
# type 
type(df["Population"])

In [31]:
# Boolean indexing 
df["Population"]  > 4000

0    True
1    True
2    True
Name: Population, dtype: bool

In [32]:
df["Country"] == "Belgium"

0     True
1    False
2    False
Name: Country, dtype: bool

In [34]:
df["Capital"] == "Brasilia"

0    False
1    False
2    False
Name: Capital, dtype: bool

In [33]:
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528