# Vectors and Matrices 

## Vectors 
- A vector has magnitude (size) and direction
- Use NumPy to create a one-dimensional array 
- Vector can be created as row or column using NumPy 

![vectors](../img/vector-mag-dir.svg)

__See More__
* https://www.mathsisfun.com/algebra/vectors.html
* https://en.wikipedia.org/wiki/Euclidean_vector

In [1]:
# Load NumPy Library 
import numpy as np 

In [2]:
# Create a vector as row 
vector_row = np.array([1, 2, 3])
print(vector_row)

[1 2 3]


In [3]:
# check type 
type(vector_row)

numpy.ndarray

In [4]:
# Create a vector as column 
vector_column = np.array([[1], [2], [3]]) 
print(vector_column) 

[[1]
 [2]
 [3]]


In [5]:
# check type 
type(vector_column)

numpy.ndarray

## Addition

In [6]:
# addition vectors
a = np.array([1, 2, 3])
print("vector_a: ", a)

b = np.array([1, 2, 3])
print("vector_b:", b)

# addition of a and b 
c = a + b
print("vector_c:", c)

vector_a:  [1 2 3]
vector_b: [1 2 3]
vector_c: [2 4 6]


## Subtraction


In [7]:
# subtraction vectors
a = np.array([1, 2, 3])
print("vector_a: ", a)

b = np.array([1, 2, 3])
print("vector_b:", b)

# addition of a and b 
c = a - b
print("vector_c:", c)

vector_a:  [1 2 3]
vector_b: [1 2 3]
vector_c: [0 0 0]


## Multiplication


In [8]:
# multiply vectors
a = np.array([1, 2, 3])
print("vector_a: ", a)

b = np.array([1, 2, 3])
print("vector_b:", b)

# addition of a and b 
c = a * b
print("vector_c:", c)

vector_a:  [1 2 3]
vector_b: [1 2 3]
vector_c: [1 4 9]


## Division

In [9]:
# divition vectors
a = np.array([1, 2, 3])
print("vector_a: ", a)

b = np.array([1, 2, 3])
print("vector_b:", b)

# addition of a and b 
c = a / b
print("vector_c:", c)

vector_a:  [1 2 3]
vector_b: [1 2 3]
vector_c: [1. 1. 1.]


## Matrix 
- In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns
- Rows run horizontally and columns run vertically
- Use NumPy to create a two-dimensional array

![matrix](../img/Matris.png)

## Matrix Order
- You can think of an $r x c$ matrix as a set of r row vectors, each having c elements; or you can think of it as a set of c column vectors, each having r elements.
- The rank of a matrix is defined as (a) the maximum number of linearly independent column vectors in the matrix or (b) the maximum number of linearly independent row vectors in the matrix. Both definitions are equivalent.
- If r is less than c, then the maximum rank of the matrix is r.
- If r is greater than c, then the maximum rank of the matrix is c.
![matrix](../img/Matrix_1000.gif)

__See More__
* https://en.wikipedia.org/wiki/Matrix_(mathematics)
* https://mathworld.wolfram.com/Matrix.html
* https://stattrek.com/matrix-algebra/matrix-rank.aspx

## Create a  matrix using `matrix()`
- Returns a matrix from an array type object ir string of data. 
- **Syntax:** `np.matrix(data)`

In [10]:
mat1 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


## Create a matrix using `array()`
- Returns a matrix 
- **Syntax:** `np.array(object)`

In [11]:
mat2 = np.array([[1, 2], [3,4], [4, 6]])
print(mat2) 

[[1 2]
 [3 4]
 [4 6]]


## Matrix Properties 

## Shape
- Returns number of rows and columns from a matrix 
- **Syntax:** `mat.shape`
    - shape[0] - returns the number of rows 
    - shape[1] - returns the number of columns 

In [12]:
mat3 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
mat3 

matrix([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [14]:
# shape 
mat3.shape

(3, 4)

In [15]:
# rows 
mat3.shape[0]

3

In [16]:
# columns 
mat3.shape[1]

4

## Size 
- Returns the number of elements from a matrix 
- **Syntax:** `array.size`

In [17]:
mat4 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
mat4

matrix([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]])

In [18]:
# size 
mat4.size

12

## Modifying matrix using `insert()`
- Adds values at a given position and axis in a matrix 
- **Syntax:** `np.insert(matrix, object, values, axis)`
    - matrix - input matrix 
    - object - index position 
    - values - matrix of values to be inserted 

In [19]:
mat5 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat5)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [20]:
# adding a new matrix `col_new` as a new column to mat5
col_new = np.matrix("1, 1, 1")
print(col_new)

[[1 1 1]]


In [21]:
# insert at column 
mat6 = np.insert(mat5, 2, col_new, axis=1)
print(mat6) 

[[ 1  2  1  3  4]
 [ 4  5  1  6  7]
 [ 7  8  1  9 10]]


In [22]:
# adding a new matrix `row_new` as a new row to mat5
row_new = np.matrix("0, 0, 0, 0")
print(row_new)

[[0 0 0 0]]


In [23]:
# insert at row 
mat7 = np.insert(mat5, 0, row_new, axis=0)
print(mat7)

[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


## Modifying matrix using `index`
- Elements of matrix can be modified using index number 
- **Syntax:**: `mat[row_index, col_index)`

In [24]:
mat_a = np.matrix("1, 2, 3, 4, 5; 5, 6, 7, 8, 9; 9, 10, 11, 12, 13")
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [25]:
mat_a[0]

matrix([[1, 2, 3, 4, 5]])

In [26]:
# change 6 with 0 
mat_a[0, 1] = 0 
mat_a

matrix([[ 1,  0,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 9, 10, 11, 12, 13]])

In [27]:
# show mat_a 
print(mat_a)

[[ 1  0  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [28]:
# extract 2nd row 
mat_a[1, :]

matrix([[5, 6, 7, 8, 9]])

In [29]:
# extract 3rd column
mat_a[:, 3]

matrix([[ 4],
        [ 8],
        [12]])

In [ ]:
# extract elements 
mat_a[1, 2]

## Matrix Operations 

In [30]:
A = np.arange(0, 20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [31]:
A.shape 

(5, 4)

In [32]:
B = np.arange(20, 40).reshape(5,4)
print(B)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [33]:
B.shape

(5, 4)

### Addition
- `np.add()`- performs element-wise addition between two matrices 
- **Syntax:** `np.add(matrix_1, matrix_2)`
![add](../img/Matrix_Addition.png)

In [34]:
# addition 
C = np.add(A, B)
C 

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [35]:
# shape of new mat 
C.shape

(5, 4)

### Subtraction
- `np.subtract()` - performs element-wise subtraction between two matrices. 
- **Syntax:** `np.subtract(matrix_1, matrix_2`) 
![sub](../img/Matrix_Subtraction.png)

In [36]:
# subtract
D = np.subtract(A, B)
D 

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [37]:
# shape of new mat 
D.shape

(5, 4)

### Transpose 
- `np.transpose()` - Permute the dimensions of an array.
- Transposing an $M \times N$ matrix flips it around the center diagonal and results in an $N \times M$ matrix.
- **Syntax:** `np.transpose(matrix)`
![transpose](../img/Matrix_Transpose.png)

In [38]:
A = np.arange(0, 20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [39]:
# transpose 
T = np.transpose(A)
T 

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [40]:
# shape of new mat 
T.shape

(4, 5)

### Multiplication 
- `np.dot()` - performs matrix multiplication between two matrices.
- **Syntax:** `np.dot(matrix_1, matrix_2)`
![mul](../img/Matrix_Multiplication.png)

In [41]:
A = np.arange(0, 20).reshape(5,4)
B = np.arange(20, 40).reshape(5,4)

In [42]:
A 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
A.shape 

(5, 4)

In [44]:
B 

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [45]:
# multiplication
np.dot(A,B) 

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

__Note__
- For matrix multiplication the number of **columns** in matrix $A$ should be equal to the number of **rows** in matrix $B$
- Here, Order of matrix $A$ = $5 \times 4$ and order of matrix $B$ = $5 \times 4$
- So, $5 \neq 4$
- That's why it shows *ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)*

In [46]:
# transpose matrix B to make it 4x5 in dimension
T = np.transpose(B)
print(T)

[[20 24 28 32 36]
 [21 25 29 33 37]
 [22 26 30 34 38]
 [23 27 31 35 39]]


In [47]:
# shape of T 
T.shape 

(4, 5)

In [48]:
A = (5 x 4) ; B = (4, 5)

SyntaxError: invalid syntax (4114966437.py, line 1)

In [49]:
# now we can perform multiplication
M = np.dot(A,T)
M 

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [50]:
# shape of M 
M.shape

(5, 5)

In [51]:
# using matmul 
np.matmul(A, T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [52]:
# using @ operator 
A @ T 

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

### Element-wise multiplication
- `np.multiply()` - performs element-wise multiplication
between two matrices. 
- **Syntax:** `np.multiply(matrix1, matrix2)`

In [53]:
# element-wise multiplication 
N = np.multiply(A, B)
N 

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

In [54]:
# shape of N 
N.shape

(5, 4)

### Division 
- `np.divide()` - performs element-wise division between two matrices. 
- **Syntax:** `np.divide(matrix_1, matrix_2)`

In [55]:
# division
H = np.divide(A, B)
H 

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [56]:
H.shape

(5, 4)

In [ ]:
S1 = ATGGGCCAAAT
S2 = AGTCCGGGGTT

In [ ]:
52% 